In [4]:
import numpy as np
#Creating Arrays
arr=np.array([1,2,3,4])
print(arr)
arra=np.array([[1,2,3,4],[5,6,7,8]])
print(arra)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#Create arrays using zeros, ones, full
arr_z=np.zeros((2,3))
print(arr)
arr_o=np.ones((2,3))
arr_f=np.full((2,3),5)
print(arr_z)
print(arr_o)
print(arr_f)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


In [11]:
#Create arrays using arange()
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Create arrays using linspace()
arr=np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [24]:
#Array Properties
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(arr))
print(np.ndim(arr))
print(np.size(arr))
print(arr.dtype)


(2, 4)
2
8
int64


In [28]:
#Indexing & Slicing
#Slice first 3 elements
arr=np.array([1,2,3,4,5,6,7])
print(arr[:3])
#Slice last 2 elements
print(arr[-2:])


[1 2 3]
[6 7]


In [38]:
#Extract a row from 2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0])
#Extract a column from 2D array
print(arr[0:2,1:2])

[1 2 3 4]
[[2]
 [6]]


In [45]:
#Operations
#Element-wise addition, subtraction, multiplication, division
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr2/arr1)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


In [44]:
#Square every element using array ** 2
arr=np.array([1,2,3,4])
print(pow(arr,2))
#Square every element using np.sqrt(), np.square()
print(np.sqrt(arr))
print(np.square(arr))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]


In [47]:
#Broadcasting
#Add a number to an array
arr=np.array([4,5,6])
print(arr+2)
#Multiply a row vector with a column vector
print(arr*4)

[6 7 8]
[16 20 24]


In [50]:
#Useful NumPy Functions
arr=np.array([1,2,3,4,5,6,7,8])
#np.mean()
print(np.mean(arr))
#np.median()
print(np.median(arr))
#np.std()
print(np.std(arr))
#np.max(), np.min()
print(np.max(arr))
print(np.min(arr))
#np.argmax(), np.argmin()
print(np.argmax(arr))
print(np.argmin(arr))

4.5
4.5
2.29128784747792
8
1
7
0


Day-5 Summary:
 Learned NumPy basics and array operations.
 Practiced indexing, slicing, and broadcasting.
 Understood how NumPy is used for ML datasets.