In [17]:
#Mini NumPy Practice
#Create a 3×3 NumPy array with numbers 1–9.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#shape
print(np.shape(arr))
#size
print(np.size(arr))
#ndim
print(np.ndim(arr))

(3, 3)
9
2


In [18]:
#Extract:
#first row
print(arr[0])
#last column
print(arr[:,-1:])

[1 2 3]
[[3]
 [6]
 [9]]


In [9]:
#Add 10 to every element.
print(arr+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [14]:
#max value
print(np.max(arr))
#min value
print(np.min(arr))
#index of max value
print(np.argmax(arr))
#index of min value
print(np.argmin(arr))

9
1
8
0


In [20]:
#Replace all values greater than 5 with 0.
arr[arr>5]=0
print(arr)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


Day-6 Summary:
 Practiced NumPy operations on 2D arrays.
 Used indexing, slicing, and basic conditions.
 Improved confidence with NumPy array manipulation.
